/**
 * ICON REGISTRY — the single mapping from SEMANTIC icon names to concrete Lucide
 * icons. Business/components reference names (`<Icon name="cart" />`), never
 * import Lucide directly, so the entire icon set can be swapped/rebranded (or
 * moved to a custom SVG set) in one place. Tree-shakes: only referenced icons
 * ship.
 */
import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  Circle,
  CircleHelp,
  Clock,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Filter,
  Flame,
  Gift,
  Grid2x2,
  Home,
  Image,
  Info,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Map,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  Package,
  Pencil,
  Phone,
  Plus,
  QrCode,
  Receipt,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Star,
  Store,
  Sun,
  Trash2,
  TrendingUp,
  Truck,
  User,
  Users,
  Utensils,
  Wifi,
  WifiOff,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

export const iconRegistry = {
  // system / nav
  dashboard: LayoutDashboard,
  home: Home,
  menu: Menu,
  settings: Settings,
  search: Search,
  filter: Filter,
  bell: Bell,
  user: User,
  users: Users,
  logout: LogOut,
  store: Store,
  grid: Grid2x2,
  more: MoreHorizontal,
  ellipsis: Ellipsis,
  // actions
  add: Plus,
  remove: Minus,
  close: X,
  edit: Pencil,
  delete: Trash2,
  copy: Copy,
  download: Download,
  refresh: RefreshCw,
  external: ExternalLink,
  linkOut: ArrowUpRight,
  // chevrons / direction
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  // status
  check: Check,
  checkCircle: CheckCircle2,
  error: XCircle,
  warning: AlertTriangle,
  info: Info,
  help: CircleHelp,
  circle: Circle,
  spinner: Loader2,
  // domain (food ordering)
  cart: ShoppingCart,
  bag: ShoppingBag,
  order: Receipt,
  package: Package,
  utensils: Utensils,
  flame: Flame,
  qr: QrCode,
  qrCode: QrCode,
  map: Map,
  shield: Shield,
  gift: Gift,
  star: Star,
  trend: TrendingUp,
  truck: Truck,
  payment: CreditCard,
  clock: Clock,
  calendar: Calendar,
  // contact / media
  mail: Mail,
  phone: Phone,
  image: Image,
  eye: Eye,
  eyeOff: EyeOff,
  // theme / connectivity
  sun: Sun,
  moon: Moon,
  wifi: Wifi,
  wifiOff: WifiOff,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;
export type { LucideIcon };
