import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { commandRegistry } from '@/platform/command';
import { searchRegistry } from '@/platform/search';
import { adminService } from './admin.service';
export function useAdminIntegrations() { const navigate = useNavigate();
  useEffect(() => commandRegistry.registerMany([
    { id: 'admin:approvals', title: 'Approve restaurant', icon: 'check', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/approvals') }, { id: 'admin:organization', title: 'Open organization', icon: 'store', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/organizations') }, { id: 'admin:user-search', title: 'Search user', icon: 'search', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/users?focus=search') }, { id: 'admin:broadcast', title: 'Broadcast notification', icon: 'bell', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/notifications?broadcast=1') }, { id: 'admin:payments', title: 'Open payments', icon: 'payment', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/payments') }, { id: 'admin:monitoring', title: 'Open monitoring', icon: 'trend', section: 'Platform actions', access: { anyRole: ['super_admin'] }, run: () => navigate('/admin/monitoring') },
  ]), [navigate]);
  useEffect(() => { const cleanups = [searchRegistry.register({ id: 'admin-organizations', label: 'Organizations', icon: 'store', access: { anyRole: ['super_admin'] }, search: async (search) => (await adminService.organizations({ search }, 1, 6)).items.map((x) => ({ id: `org:${x.id}`, title: x.name, subtitle: x.status, icon: 'store', group: 'Organizations', href: `/admin/organizations?id=${x.id}` })) }), searchRegistry.register({ id: 'admin-users', label: 'Users', icon: 'users', access: { anyRole: ['super_admin'] }, search: async (search) => (await adminService.users({ search }, 1, 6)).items.map((x) => ({ id: `user:${x.id}`, title: x.name ?? x.email, subtitle: x.email, icon: 'users', group: 'Users', href: `/admin/users?id=${x.id}` })) }), searchRegistry.register({ id: 'admin-payments', label: 'Payments', icon: 'payment', access: { anyRole: ['super_admin'] }, search: async (search) => (await adminService.payments({ search }, 1, 6)).items.map((x) => ({ id: `payment:${x.id}`, title: x.id, subtitle: `${x.provider ?? ''} ${x.status}`, icon: 'payment', group: 'Payments', href: '/admin/payments' })) })]; return () => cleanups.forEach((fn) => fn()); }, []);
}
